# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project/UIFiles/AppPageUI_CompoundInterest.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModulePage(object):
    def setupUi(self, ModulePage):
        ModulePage.setObjectName("ModulePage")
        ModulePage.resize(305, 381)
        font = QtGui.QFont()
        font.setPointSize(12)
        ModulePage.setFont(font)
        self.label_1 = QtWidgets.QLabel(ModulePage)
        self.label_1.setGeometry(QtCore.QRect(40, 10, 91, 41))
        self.label_1.setObjectName("label_1")
        self.input_1 = QtWidgets.QLineEdit(ModulePage)
        self.input_1.setGeometry(QtCore.QRect(150, 19, 113, 21))
        self.input_1.setObjectName("input_1")
        self.input_2 = QtWidgets.QLineEdit(ModulePage)
        self.input_2.setGeometry(QtCore.QRect(150, 60, 113, 21))
        self.input_2.setObjectName("input_2")
        self.calculateButton = QtWidgets.QPushButton(ModulePage)
        self.calculateButton.setGeometry(QtCore.QRect(180, 320, 101, 31))
        self.calculateButton.setObjectName("calculateButton")
        self.label_2 = QtWidgets.QLabel(ModulePage)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 81, 41))
        self.label_2.setObjectName("label_2")
        self.resultLabel = QtWidgets.QLabel(ModulePage)
        self.resultLabel.setGeometry(QtCore.QRect(70, 250, 161, 41))
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")
        self.resetButton = QtWidgets.QPushButton(ModulePage)
        self.resetButton.setGeometry(QtCore.QRect(20, 320, 101, 31))
        self.resetButton.setObjectName("resetButton")
        self.label_3 = QtWidgets.QLabel(ModulePage)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 81, 41))
        self.label_3.setObjectName("label_3")
        self.input_3 = QtWidgets.QLineEdit(ModulePage)
        self.input_3.setGeometry(QtCore.QRect(150, 100, 113, 21))
        self.input_3.setObjectName("input_3")
        self.label_4 = QtWidgets.QLabel(ModulePage)
        self.label_4.setGeometry(QtCore.QRect(40, 120, 101, 61))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.input_4 = QtWidgets.QLineEdit(ModulePage)
        self.input_4.setGeometry(QtCore.QRect(150, 150, 113, 21))
        self.input_4.setObjectName("input_4")

        self.retranslateUi(ModulePage)
        QtCore.QMetaObject.connectSlotsByName(ModulePage)

    def retranslateUi(self, ModulePage):
        _translate = QtCore.QCoreApplication.translate
        ModulePage.setWindowTitle(_translate("ModulePage", "Form"))
        self.label_1.setText(_translate("ModulePage", "Principal ($)"))
        self.calculateButton.setText(_translate("ModulePage", "Calculate"))
        self.label_2.setText(_translate("ModulePage", "Rate (%)"))
        self.resultLabel.setText(_translate("ModulePage", "Your Result"))
        self.resetButton.setText(_translate("ModulePage", "Reset"))
        self.label_3.setText(_translate("ModulePage", "Periods (t)"))
        self.label_4.setText(_translate("ModulePage", "Compounds per period (n)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModulePage = QtWidgets.QWidget()
    ui = Ui_ModulePage()
    ui.setupUi(ModulePage)
    ModulePage.show()
    sys.exit(app.exec_())
