# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project/UIFiles/LandingPageButton.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LandingPageButton(object):
    def setupUi(self, LandingPageButton):
        LandingPageButton.setObjectName("LandingPageButton")
        LandingPageButton.resize(241, 33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LandingPageButton.sizePolicy().hasHeightForWidth())
        LandingPageButton.setSizePolicy(sizePolicy)
        LandingPageButton.setMinimumSize(QtCore.QSize(0, 0))
        self.appButton1 = QtWidgets.QPushButton(LandingPageButton)
        self.appButton1.setGeometry(QtCore.QRect(0, 0, 241, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appButton1.sizePolicy().hasHeightForWidth())
        self.appButton1.setSizePolicy(sizePolicy)
        self.appButton1.setMinimumSize(QtCore.QSize(0, 0))
        self.appButton1.setObjectName("appButton1")

        self.retranslateUi(LandingPageButton)
        QtCore.QMetaObject.connectSlotsByName(LandingPageButton)

    def retranslateUi(self, LandingPageButton):
        _translate = QtCore.QCoreApplication.translate
        LandingPageButton.setWindowTitle(_translate("LandingPageButton", "Form"))
        self.appButton1.setText(_translate("LandingPageButton", "Module 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LandingPageButton = QtWidgets.QWidget()
    ui = Ui_LandingPageButton()
    ui.setupUi(LandingPageButton)
    LandingPageButton.show()
    sys.exit(app.exec_())
