# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project/UIFiles/MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(300, 451)
        MainWindow.setMinimumSize(QtCore.QSize(300, 450))
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(4.0)
        self.mainWidget = QtWidgets.QWidget(MainWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.mainWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 301, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(6)
        self.mainLayout.setObjectName("mainLayout")
        self.headerWidget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.headerWidget.setMaximumSize(QtCore.QSize(16777215, 35))
        self.headerWidget.setObjectName("headerWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.headerWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 0, 301, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.header = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.header.setContentsMargins(0, 0, 0, 0)
        self.header.setSpacing(0)
        self.header.setObjectName("header")
        self.backButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.backButton.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(True)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color:#f8f8ff; \n"
"border: none;\n"
"")
        self.backButton.setFlat(False)
        self.backButton.setObjectName("backButton")
        self.header.addWidget(self.backButton)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setMaximumSize(QtCore.QSize(16777215, 30))
        self.line.setStyleSheet("color: black;")
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.header.addWidget(self.line)
        self.headerLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.headerLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.headerLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.headerLabel.setFont(font)
        self.headerLabel.setStyleSheet("background-color: #f8f8ff; color: black;")
        self.headerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.headerLabel.setObjectName("headerLabel")
        self.header.addWidget(self.headerLabel)
        self.mainLayout.addWidget(self.headerWidget)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.mainLayout.addWidget(self.line_2)
        self.bodyWidget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.bodyWidget.setObjectName("bodyWidget")
        self.bodyStackedWidget = QtWidgets.QStackedWidget(self.bodyWidget)
        self.bodyStackedWidget.setGeometry(QtCore.QRect(0, 0, 300, 400))
        self.bodyStackedWidget.setObjectName("bodyStackedWidget")
        self.landingPage = QtWidgets.QWidget()
        self.landingPage.setObjectName("landingPage")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.landingPage)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 301, 411))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.landingPageVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.landingPageVLayout.setContentsMargins(20, 0, 20, 0)
        self.landingPageVLayout.setObjectName("landingPageVLayout")
        self.bodyStackedWidget.addWidget(self.landingPage)
        self.mainLayout.addWidget(self.bodyWidget)
        MainWindow.setCentralWidget(self.mainWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Some Finance App"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.headerLabel.setText(_translate("MainWindow", "Main Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
