# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project/UIFiles/MorseCodeUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModulePage(object):
    def setupUi(self, ModulePage):
        ModulePage.setObjectName("ModulePage")
        ModulePage.resize(300, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(ModulePage)
        self.verticalLayout.setContentsMargins(6, 2, 6, 2)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(ModulePage)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.input_plaintext = QtWidgets.QPlainTextEdit(ModulePage)
        self.input_plaintext.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.input_plaintext.setObjectName("input_plaintext")
        self.verticalLayout.addWidget(self.input_plaintext)
        self.label_5 = QtWidgets.QLabel(ModulePage)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.output_ciphertext = QtWidgets.QTextBrowser(ModulePage)
        self.output_ciphertext.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.output_ciphertext.setObjectName("output_ciphertext")
        self.verticalLayout.addWidget(self.output_ciphertext)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.resetButton = QtWidgets.QPushButton(ModulePage)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout_2.addWidget(self.resetButton, 0, 0, 1, 1)
        self.encodeButton = QtWidgets.QPushButton(ModulePage)
        self.encodeButton.setObjectName("encodeButton")
        self.gridLayout_2.addWidget(self.encodeButton, 0, 1, 1, 1)
        self.decodeButton = QtWidgets.QPushButton(ModulePage)
        self.decodeButton.setObjectName("decodeButton")
        self.gridLayout_2.addWidget(self.decodeButton, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(ModulePage)
        QtCore.QMetaObject.connectSlotsByName(ModulePage)

    def retranslateUi(self, ModulePage):
        _translate = QtCore.QCoreApplication.translate
        ModulePage.setWindowTitle(_translate("ModulePage", "Form"))
        self.label_4.setText(_translate("ModulePage", "Input Text"))
        self.label_5.setText(_translate("ModulePage", "Output Text"))
        self.resetButton.setText(_translate("ModulePage", "Reset"))
        self.encodeButton.setText(_translate("ModulePage", "Encode"))
        self.decodeButton.setText(_translate("ModulePage", "Decode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModulePage = QtWidgets.QWidget()
    ui = Ui_ModulePage()
    ui.setupUi(ModulePage)
    ModulePage.show()
    sys.exit(app.exec_())
